cards/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='cards-home'),
    path(
        'create_subject/',
        views.create_subject,
        name='create_subject'
    ),
    path(
        'subject/<int:subject_id>/',
        views.subject_detail,
        name='subject_detail'
    ),
    path(
        'subject/<int:subject_id>/edit/',
        views.edit_subject,
        name='edit_subject'
    ),
    path(
        'subject/<int:subject_id>/delete/',
        views.delete_subject,
        name='delete_subject'
    ),
    path(
        'subject/<int:subject_id>/create_deck/',
        views.create_deck,
        name='create_deck'
    ),
    path(
        'deck/<int:deck_id>/',
        views.deck_detail,
        name='deck_detail'
    ),
    path(
        'deck/<int:deck_id>/edit/',
        views.edit_deck,
        name='edit_deck'
    ),
    path(
        'deck/<int:deck_id>/delete/',
        views.delete_deck,
        name='delete_deck'
    ),
    path(
        'deck/<int:deck_id>/card/',
        views.manage_card,
        name='create_card'
    ),
    path(
        'deck/<int:deck_id>/card/<int:card_id>/',
        views.manage_card,
        name='edit_card'
    ),
    path(
        'card/<int:card_id>/delete/',
        views.delete_card,
        name='delete_card'
    ),
    path(
        'deck/<int:deck_id>/quiz/',
        views.quiz_view,
        name='quiz_view'
    ),
]

flashcards/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from users import views as user_views
from cards import views as cards_views

urlpatterns = [
    path('', include('cards.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', user_views.user_login, name='login'),
    path(
        'logout/',
        auth_views.LogoutView.as_view(template_name='logout.html'),
        name='logout'
    ),
    path('profile/', user_views.profile, name='profile'),
]

# Custom error handlers
handler404 = 'cards.views.handler404'

# Enable admin page when DEBUG is set to True
if settings.DEBUG == 'True':
    urlpatterns += path('admin/', admin.site.urls),

cards/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.files.base import ContentFile
from django.core.exceptions import ValidationError
from PIL import Image
from io import BytesIO
import os


# Create your models here.
class Subject(models.Model):
    """
    Represents a subject under which decks of flashcards can be categorized.

    Attributes:
        name (str): The name of the subject.
        creator (User): The user who created the subject.
        created_at (datetime): The date and time when the subject was created.
    """
    name = models.CharField(max_length=100)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class Deck(models.Model):
    """
    Represents a deck of cards within a subject.

    Attributes:
        name (str): The name of the deck.
        description (str): A description of the deck.
        subject (Subject): The subject to which the deck belongs.
        created_at (datetime): The date and time when the deck was created.
    """
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


def card_img(instance, filename):
    """
    Determines the path where the card image will be stored.

    Arguments:
        instance (Card): The card instance.
        filename (str): The original filename of the uploaded image.

    Returns:
        str: The path where the card image will be stored.
    """
    return 'user_{0}/{1}'.format(
        instance.deck.subject.creator.username,
        filename
    )


class Card(models.Model):
    """
    Represents a flashcard within a deck.

    Attributes:
        question (str): The question or front side of the card.
        question_image (ImageField): The image for the question side.
        answer (str): The answer or back side of the card.
        answer_image (ImageField): The image for the answer side.
        deck (Deck): The deck to which the card belongs.
        created_at (datetime): The date and time when the card was created.
    """
    question = models.TextField(blank=True)
    question_image = models.ImageField(
        upload_to=card_img,
        blank=True,
        null=True
    )
    answer = models.TextField(blank=True)
    answer_image = models.ImageField(
        upload_to=card_img,
        blank=True,
        null=True
    )
    deck = models.ForeignKey(Deck, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    def clean(self):
        """
        Validates that either text or image is provided for both the
        question and the answer.
        """
        if not self.question and not self.question_image:
            raise ValidationError(
                'You must provide either a question or an image.'
            )
        if not self.answer and not self.answer_image:
            raise ValidationError(
                'You must provide either a answer or an image.'
            )

    def save(self, *args, **kwargs):
        """
        Overridden save method to process images before saving.
        """
        self.clean()
        # Process question image
        if self.question_image:
            self.process_image(self.question_image)

        # Process answer image
        if self.answer_image:
            self.process_image(self.answer_image)

        super().save(*args, **kwargs)

    def process_image(self, image_field):
        """
        Processes the image by resizing and converting it to WEBP format.

        Arguments:
            image_field (ImageField): The image field to process.
        """
        MAX_SIZE = (800, 800)
        with Image.open(image_field) as img:
            # Resize the image if it's bigger than 800px
            img.thumbnail(MAX_SIZE)

            # Create a BytesIO object to save the image
            in_mem_file = BytesIO()
            img.save(in_mem_file, format='WEBP')
            in_mem_file.seek(0)

            # Change the file extension to .webp
            filename = os.path.basename(image_field.name)
            image_field.save(
                filename,
                ContentFile(in_mem_file.read()),
                save=False
            )

cards/forms.py
from django import forms
from .models import Subject, Deck, Card


class SubjectForm(forms.ModelForm):
    """
    A form for creating and updating Subject instances.
    """
    class Meta:
        model = Subject
        fields = ['name']


class DeckForm(forms.ModelForm):
    """
    A form for creating and updating Deck instances.
    """
    class Meta:
        model = Deck
        fields = ['name', 'description']


class CardForm(forms.ModelForm):
    """
    A form for creating and updating Card instances.
    """
    class Meta:
        model = Card
        fields = ['question', 'question_image', 'answer', 'answer_image']

cards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse
from .forms import SubjectForm, DeckForm, CardForm
from .models import Subject, Deck, Card
from django.core.serializers import serialize
import json


# Home view
def home(request):
    """
    Render the home page of the application.

    For authenticated users, this view displays a list of subjects
    created by them.
    For non-authenticated users, a generic welcome page is displayed.
    """
    if request.user.is_authenticated:
        # Render a template with user-specific content for logged-in users
        user_subjects = Subject.objects.filter(creator=request.user)
        return render(
            request,
            'cards/home.html',
            {'user_subjects': user_subjects}
        )
    else:
        # Render a generic template (index.html) for non-logged-in users
        return render(request, 'cards/index.html')


# SUBJECTS
# Create Subject
@login_required
def create_subject(request):
    """
    Create a new subject.

    Allows a logged-in user to create a new subject. The user is redirected
    to the subject detail page upon successful creation
    """
    if request.method == 'POST':
        form = SubjectForm(request.POST)
        if form.is_valid():
            subject = form.save(commit=False)
            subject.creator = request.user
            subject.save()
            return redirect('subject_detail', subject_id=subject.id)
    else:
        form = SubjectForm()
    return render(request, 'cards/subject_create.html', {'form': form})


# Subject Details
@login_required
def subject_detail(request, subject_id):
    """
    Display the details of a specific subject.

    Retrieves and displays details of a subject only if the
    logged in user is the creator of the subject, if not the
    user is denied access.
    """
    subject = get_object_or_404(Subject, id=subject_id, creator=request.user)
    return render(request, 'cards/subject_detail.html', {'subject': subject})


# Edit Subject
@login_required
def edit_subject(request, subject_id):
    """
    Edit an existing subject.

    Allows the creator of the subject to edit its details.
    After a successful edit the user is redirected to the
    detail page.
    """
    subject = get_object_or_404(Subject, id=subject_id, creator=request.user)

    if request.method == 'POST':
        form = SubjectForm(request.POST, instance=subject)
        if form.is_valid():
            form.save()
            return redirect('subject_detail', subject_id=subject.id)
    else:
        form = SubjectForm(instance=subject)
    return render(
        request,
        'cards/subject_edit.html',
        {'form': form, 'subject': subject}
    )


# Delete Subject
@login_required
def delete_subject(request, subject_id):
    """
    Delete a existing subject.

    Allows the creator of the subject to delete the subject
    with all the decks/cards belonging to it. After a
    successful deletion, the user is redirected to the
    home page.
    """
    subject = get_object_or_404(Subject, id=subject_id, creator=request.user)

    subject.delete()
    messages.success(request, "Subject deleted successfully")
    return redirect('cards-home')


# DECKS
# Create Deck
@login_required
def create_deck(request, subject_id):
    """
    Create a new deck.

    Allows a logged-in user to create a new deck. The user is redirected
    to the deck detail page upon successful creation
    """
    subject = get_object_or_404(Subject, id=subject_id, creator=request.user)

    if request.method == 'POST':
        form = DeckForm(request.POST)
        if form.is_valid():
            deck = form.save(commit=False)
            deck.subject = subject
            deck.save()
            return redirect('deck_detail', deck_id=deck.id)
    else:
        form = DeckForm()
    return render(
        request,
        'cards/deck_create.html',
        {'form': form, 'subject': subject}
    )


# Deck Details
def deck_detail(request, deck_id):
    """
    Display the details of a specific deck.

    Retrieves and displays details of a deck only if the
    logged in user is the creator of the subject, if not the
    user is denied access.
    """
    deck = get_object_or_404(Deck, id=deck_id, subject__creator=request.user)
    cards = deck.card_set.all()
    num_cards = deck.card_set.count()
    return render(
        request,
        'cards/deck_detail.html',
        {'deck': deck, 'cards': cards, 'num_cards': num_cards}
    )


# Edit Deck
@login_required
def edit_deck(request, deck_id):
    """
    Edit an existing deck.

    Allows the creator of the subject to edit the decks details.
    After a successful edit the user is redirected to the
    detail page.
    """
    deck = get_object_or_404(Deck, id=deck_id, subject__creator=request.user)

    if request.method == 'POST':
        form = DeckForm(request.POST, instance=deck)
        if form.is_valid():
            form.save()
            return redirect('deck_detail', deck_id=deck.id)
    else:
        form = DeckForm(instance=deck)
    num_cards = deck.card_set.count()
    return render(
        request,
        'cards/deck_edit.html',
        {'form': form, 'deck': deck, 'num_cards': num_cards}
    )


# Delete Deck
@login_required
def delete_deck(request, deck_id):
    """
    Delete a existing deck.

    Allows the creator of the subject to delete the deck
    with all the cards belonging to it. After a
    successful deletion, the user is redirected to the
    subject detail page.
    """
    deck = get_object_or_404(Deck, id=deck_id, subject__creator=request.user)

    deck.delete()
    messages.success(request, "Deck deleted successfully")
    return redirect('subject_detail', subject_id=deck.subject.id)


# CARDS
# Create and update Card
@login_required
def manage_card(request, deck_id, card_id=None):
    """
    Handles creation and updating of cards.

    If a card ID is provided, the view functions as an edit form for the
    specified card.
    If no card ID is provided, the view presents a form
    for creating a new card.
    """
    deck = get_object_or_404(Deck, id=deck_id, subject__creator=request.user)
    if card_id:
        card = get_object_or_404(Card, id=card_id, deck=deck)
        action = "Edit"
    else:
        card = None
        action = "Create"

    if request.method == 'POST':
        form = CardForm(request.POST, request.FILES, instance=card)
        if form.is_valid():
            card = form.save(commit=False)
            card.deck = deck
            card.save()
            form = CardForm()
    else:
        form = CardForm(instance=card)
    cards = Card.objects.filter(deck=deck).order_by('-created_at')
    return render(request, 'cards/card_form.html', {
        'form': form,
        'deck': deck,
        'cards': cards,
        'action': action
    })


# Delete Card
@login_required
def delete_card(request, card_id):
    """
    Delete an existing card.

    Allows the creator of the subject to delete the card.
    After a successful deletion, the user is redirected back to the
    create card page to continue managing other cards within the deck.
    """
    card = get_object_or_404(
        Card,
        id=card_id,
        deck__subject__creator=request.user
    )
    deck_id = card.deck.id
    card.delete()
    messages.success(request, "Card deleted successfully")
    return redirect('create_card', deck_id=deck_id)


# Quiz view
@login_required
def quiz_view(request, deck_id):
    """
    Renders the quiz page with a set of cards from a specified deck.
    Ensures that all necessary content is available for front-end parsing.
    """
    deck = get_object_or_404(Deck, pk=deck_id, subject__creator=request.user)
    cards = deck.card_set.all()
    data = []
    for card in cards:
        if card.question_image:
            question_img = request.build_absolute_uri(card.question_image.url)
        else:
            question_img = ''
        if card.answer_image:
            answer_img = request.build_absolute_uri(card.answer_image.url)
        else:
            answer_img = ''
        card_data = {
            'question': card.question,
            'answer': card.answer,
            'question_image': question_img,
            'answer_image': answer_img
        }
        data.append(card_data)
    return render(request, 'cards/quiz.html', {'deck': deck, 'cards': data})


# 404 handler
def handler404(request, exception):
    """
    Renders the 404 page.
    """
    return render(request, 'cards/404.html', status=404)

cards/templates/cards/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
    <head>
        <!-- Meta tags -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="FlashCards!">
        <meta name="keywords" content="FlashCards, flash cards, studying, school, learn, learning">
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <!-- Custom CSS-->
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <!-- Favicon -->
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
        <!-- Title -->
        <title>FlashCards</title>
    </head>
    <body>
        <header class="site-header">
            <nav class="navbar navbar-dark bg-steel fixed-top">
                <div class="container">
                    <a class="navbar-brand mr-4" href="{% url 'cards-home' %}">FlashCards</a>
                    <div class="me-4">
                        <!-- Theme Toggle -->
                        <input type="checkbox" class="btn-check" id="darkModeSwitch" checked autocomplete="off">
                        <label class="btn border-0" for="darkModeSwitch"><i class="bi bi-moon-stars-fill"></i></label>
                        <!-- Navigation bar toggle -->
                        {% if user.is_authenticated %}
                        <img src="{{ user.profile.image.url }}" alt="{{ user.first_name }}" style="width:40px;" class="rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                        <div class="collapse navbar-collapse" id="navbarToggle" align="right">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'profile' %}">{{ user.first_name }} {{ user.last_name }}</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                                </li>
                            </ul>
                        </div>
                        {% else %}
                            <a href="{% url 'login' %}" class="btn btn-light">Login</a>
                        {% endif %}
                    </div>
                </div>
            </nav>
        </header>
        <main class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                    {% block content %}{% endblock %}
                </div>
            </div>
            <!-- Confirmation Modal -->
            <div class="modal fade" id="confirmDeleteModal" tabindex="-1" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="confirmDeleteModalLabel">Confirm Deletion</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            Are you sure you want to delete this item?
                        </div>    
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                            <a href="#" class="btn btn-danger" id="deleteConfirmBtn">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <!-- Custom JavaScript -->
        <script src="{% static 'js/script.js' %}"></script>
        {% block extra_js %}
        {% endblock %}
        <!-- Bootstrap Js -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
</html>

cards/templates/cards/card_form.html
{% extends "cards/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section border border-secondary-subtle rounded">
        <div class="row">
            <div class="col-4">
                <a href="{% url 'deck_detail' deck_id=deck.id %}" class="btn btn-secondary"><i class="bi bi-arrow-left-square-fill"></i> Back</a>
            </div>
            <div class="col-8 text-end">
                {% if action == "Edit" %}
                    <div class="btn-group">
                        <a href="{% url 'create_card' deck_id=deck.id %}" class="btn btn-success">Create a new Card</i></a>
                    </div>
                {% endif %}
            </div>
        </div>
        <h2>{{ action }} Card</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="form-group text-end">
                {% if action == "Edit" %}
                    <button class="btn btn-success" type="submit">Save Changes</button>
                {% else %}
                    <button class="btn btn-success" type="submit">{{ action }} Card</button>
                {% endif %}
            </div>
        </form>
        {% if cards.exists %}
            <h2>Existing Cards</h2>
            <ul>
                <div class="row">
                    <div class="col-md-4">
                        Question
                    </div>
                    <div class="col-md-4 offset-md-4">
                        Answer
                    </div>
                </div>
                <div class="d-flex flex-column bd-highlight mb-3 row-gap-3">
                    {% for card in cards %}
                    <div class="row bd-highlight border border-secondary-subtle rounded">
                        <div class="col border border-secondary-subtle rounded">
                            <div class="col">
                                {{ card.question }}
                            </div>
                            {% if card.question_image %}
                            <div class="col">
                                    <img src="{{ card.question_image.url }}" class="img-thumbnail rounded" alt="Question Image">
                            </div>
                            {% endif %}
                        </div>
                        <div class="col border border-secondary-subtle rounded">
                            <div class="col">
                                {{ card.answer }}
                            </div>
                            <div class="col">
                                {% if card.answer_image %}
                                    <img src="{{ card.answer_image.url }}" class="img-thumbnail rounded" alt="Answer Image">
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-auto d-flex flex-column">
                            <a href="{% url 'edit_card' deck_id=deck.id card_id=card.id %}" class="btn btn-outline-secondary btn-sm mt-2"><i class="bi bi-pencil-square"></i></a>
                            <a href="#" class="btn btn-outline-danger btn-sm mt-auto mb-2" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" data-delete-url="{% url 'delete_card' card_id=card.id %}"><i class="bi bi-trash"></i></a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </ul>
        {% endif %}
    </div>
{% endblock content%}

cards/templates/cards/create_card.html
{% extends "cards/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border_bottom mb-4">
                    Create Card
                </legend>
                {{ form | crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Create Card</button>
            </div>
        </form>
    </div>
{% endblock content%}

cards/templates/cards/create_deck.html
{% extends "cards/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border_bottom mb-4">
                    Create Deck
                </legend>
                {{ form | crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Create Deck</button>
            </div>
        </form>
    </div>
{% endblock content%}

cards/templates/cards/create_subject.html
{% extends "cards/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border_bottom mb-4">
                    Create Subject
                </legend>
                {{ form | crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Create Subject</button>
            </div>
        </form>
    </div>
{% endblock content%}

cards/templates/cards/deck_create.html
{% extends "cards/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section border border-secondary-subtle rounded">
        <div class="row">
            <div class="col-4">
                <a href="{% url 'subject_detail' subject_id=subject.id %}" class="btn btn-secondary"><i class="bi bi-arrow-left-square-fill"></i> Back</a>
            </div>
    </div>
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border_bottom mb-4">
                    Create Deck
                </legend>
                {{ form | crispy }}
            </fieldset>
            <div class="form-group text-end">
                <button class="btn btn-success" type="submit">Create Deck</button>
            </div>
        </form>
    </div>
{% endblock content%}

cards/templates/cards/deck_detail.html
{% extends "cards/base.html" %}
{% block content %}
    <div class="content-section border border-secondary-subtle rounded">
        <div class="row">
            <div class="col-4">
                <a href="{% url 'subject_detail' subject_id=deck.subject.id %}" class="btn btn-secondary"><i class="bi bi-arrow-left-square-fill"></i> Back</a>
            </div>
            <div class="col-8 text-end">
            {% if deck.subject.creator == user %}
                <div class="btn-group">
                    <a href="{% url 'create_card' deck_id=deck.id %}" class="btn btn-success">Manage Cards <i class="bi bi-pencil-square"></i></a>
                </div>
            </div>
            {% endif %}
        </div>
        <div class="g-2 p-3">
            <h1>{{ deck.name }}</h1>
            <p>{{ deck.description }}</p>
            {% if num_cards > 0%}
            <div class="d-grid gap-2 col-6 mx-auto">
                <a href="{% url 'quiz_view' deck_id=deck.id %}" class="btn btn-success btn-lg">Start Quiz <span class="badge text-bg-light">{{ num_cards }}</span></a>
            </div>
            {% else %}
                <div class="d-grid gap-2 col-6 mx-auto">
                    <p>There are no cards in this deck yet. Let's add some!</p>
                    <a href="{% url 'create_card' deck_id=deck.id %}" class="btn btn-success">Add Cards <i class="bi bi-pencil-square"></i></a>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock content%}

cards/templates/cards/subject_detail.html
{% extends "cards/base.html" %}
{% block content %}
    <div class="content-section border border-secondary-subtle rounded">
        <div class="row">
            <div class="col-4">
                <a href="{% url 'cards-home' %}" class="btn btn-secondary"><i class="bi bi-arrow-left-square-fill"></i> Back</a>
            </div>
            <div class="col-8 text-end">
                {% if subject.creator == user %}
                    <div class="btn-group">
                        <a href="{% url 'create_deck' subject_id=subject.id %}" class="btn btn-success"><i class="bi bi-plus-square-fill"></i> Add Deck</a>
                    </div>
                {% endif %}
            </div>
        </div>
        <h1>{{ subject.name }}</h1>
        <h2>Decks</h2>
            <ul class="list-group">
                {% for deck in subject.deck_set.all %}
                    <li class="list-group-item d-flex justify-content-between align-items-center fs-5 text">
                        <a href="{% url 'deck_detail' deck_id=deck.id %}" class="list-group-item-action">{{ deck.name }}</a>
                        <div class="btn-group" role="group">
                            <a href="{% url 'edit_deck' deck_id=deck.id %}" class="btn btn-outline-secondary btn-sm"><i class="bi bi-pencil-square"></i></a>
                            <a href="#" class="btn btn-outline-danger btn-sm" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" data-delete-url="{% url 'delete_deck' deck_id=deck.id %}"><i class="bi bi-trash"></i></a>
                        </div>
                    </li>
                {% empty %}
                    <li>No decks yet.</li>
                {% endfor %}
            </ul>
    </div>
{% endblock content%}

cards/templates/cards/subject_edit.html
{% extends "cards/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section border border-secondary-subtle rounded">
    <div class="row">
        <div class="col-4">
            <a href="{% url 'cards-home' %}" class="btn btn-secondary"><i class="bi bi-arrow-left-square-fill"></i> Back</a>
        </div>
    </div>
    <h2>Edit Subject</h2>
    <form method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <div class="text-end">
            <button type="submit" class="btn btn-success">Save changes</button>
        </div>
    </form>
</div>
{% endblock content %}